# Build for amd64 and arm64 and publish to DockerHub
name: build

on:
  push:
    branches: [ main ]

jobs:

  buildx:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3.3.0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Echo available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the images
        run: |
          docker buildx build \
          --push \
          --tag ${{ secrets.DOCKER_USERNAME }}/teslamate-abrp:latest \
          --platform linux/amd64,linux/arm64,linux/arm/v7 . 
